//
//  MainSceneInteractor.swift
//  ClvrtcTaskFour
//
//  Created by Artyom Beldeiko on 21.01.23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainSceneBusinessLogic
{
  func doSomething(request: MainScene.Something.Request)
}

protocol MainSceneDataStore {

}

class MainSceneInteractor: MainSceneBusinessLogic, MainSceneDataStore {
  var presenter: MainScenePresentationLogic?
  var worker: MainSceneWorker?
  
  func doSomething(request: MainScene.Something.Request) {
    worker = MainSceneWorker()
    worker?.doSomeWork()
    
    let response = MainScene.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
