//
//  MapSceneModels.swift
//  ClvrtcTaskFour
//
//  Created by Artyom Beldeiko on 21.01.23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MapScene {
  
  enum Data {
    struct Request {

    }
      
    struct Response {
        var atmData: [ATM]?
        var branchBankData: [BankBranch]?
        var serviceTerminalData: [ServiceTerminal]?
        var annotatedATMData: [MKAnnotatedATM]?
        var annotatedBranchBankData: [MKAnnotatedBranchBank]?
        var annotatedServiceTerminalData: [MKAnnotatedServiceTerminal]?
    }
      
    struct ViewModel {
        var MKAnnotatedATM: [MKAnnotatedATM]?
        var MKAnnotatedServiceTerminal: [MKAnnotatedServiceTerminal]?
        var MKAnnotatedBranchBank: [MKAnnotatedBranchBank]?
    }
  }
}
